dist: bionic
language: cpp
compiler: gcc

python:
  - "3.7"      # current default Python on Travis CI
git:
  depth: 1
branches:
  only:
    - master
    - staging
addons:
  apt:
    update: true
    sources:
    packages:
      - g++
      - libboost-all-dev
      - lcov
      # - libtbb-dev
      - wget
install:
#  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
script:
  - export PYTHON_EXECUTABLE=`which python3`
  - export PYTHON_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")
  - export PYTHON_LIBRARY=$(python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - make
  - ctest --verbose
  - cd ..
  - sleep 10
after_success:
  - chmod +x ./runCoverage.sh
  - ./runCoverage.sh -t 1 -s 1
  - sleep 10
